Repository Ragnacodes/Legato-Frontend, pull requests merged in 2021-05, with the labels that each got.

#45 Feature/connections v2
  package.json
  src/actions/connections.js
  src/components/Connections/AddConnection.js
  src/components/Connections/Connection.js
  src/components/Connections/Connections.js
  src/components/Connections/Redirect.js
  src/reducers/connections.js
Labels: enhancement

#44 Feature/sketchpad telegram
  src/components/Services/Telegram/SendMessage/Form.js
  src/components/Services/Telegram/SendMessage/Node.js
  src/components/Services/Telegram/getChatMember/Form.js
  src/components/Services/Telegram/getChatMember/Node.js
  src/components/Services/nodeTypes.js
  src/components/Services/services.js
  src/styles/sketchpad/sketchpad.scss
Labels: feature

#46 Feature/sketchpad spotify
  src/actions/auth.js
  src/actions/signup.js
  src/actions/spotify.js
  src/components/LoginSignUp/LoginForm.js
  src/components/LoginSignUp/SignUpForm.js
  src/components/Scenarios/ScenarioNodes.js
  src/components/Services/Spotify/GetTopTracks/Form.js
  src/components/Services/Spotify/GetTopTracks/Node.js
  src/components/Services/Spotify/SaveToPlaylist/Form.js
  src/components/Services/Spotify/SaveToPlaylist/Node.js
  src/components/Services/Spotify/SidebarItem.js
  src/components/Services/Spotify/WatchPlaylist/Form.js
  src/components/Services/Spotify/WatchPlaylist/Node.js
  src/components/Services/Webhook/CustomWebhook/Form.js
  src/components/Services/Webhook/WebhookResponse/Form.js
  src/components/Services/nodeTypes.js
  src/components/Services/services.js
  src/components/Webhooks/Webhooks.js
  src/reducers/spotify.js
  src/store/configureStore.js
  src/styles/service-forms.scss
  src/styles/styles.scss
Labels: feature

#54 Feature/scheduling
  src/actions/sketchpad.js
  src/components/Services/Spotify/GetTopTracks/Form.js
  src/components/Sketchpad/Scheduling/Interval.js
  src/components/Sketchpad/Scheduling/Once.js
  src/components/Sketchpad/Scheduling/Scheduling.js
  src/components/Sketchpad/SketchpadControl.js
  src/styles/scheduling.scss
  src/styles/styles.scss
  src/utils/axiosConfig.js
Labels: feature

#56 Feature/sketchpad spotify v2
  src/actions/spotify.js
  src/components/Services/Spotify/SaveToPlaylist/Form.js
  src/components/Services/Spotify/SaveToPlaylist/TrackInfo.js
  src/components/Services/Spotify/WatchPlaylist/Form.js
  src/reducers/spotify.js
  src/tests/components/LoginSignUp/LoginForm.test.js
  src/tests/components/LoginSignUp/SignUpForm.test.js
Labels: enhancement

#57 Feature/webhook history
  package.json
  src/actions/webhooks.js
  src/components/Connections/AddConnection.js
  src/components/Connections/ConnectionsPage.js
  src/components/SSH/ConnectionForm.js
  src/components/SSH/ConnectionFormModal.js
  src/components/SSH/ExtractKey.js
  src/components/SSH/Keys.js
  src/components/SSH/UserKey.js
  src/components/SSH/UserPass.js
  src/components/Services/SSH/ExecuteCommand/Form.js
  src/components/Services/SSH/ExecuteCommand/Node.js
  src/components/Webhooks/GeneralSettings.js
  src/components/Webhooks/QueueDetails.js
  src/components/Webhooks/Webhook.js
  src/components/Webhooks/WebhookSettings.js
  src/components/Webhooks/WebhookSettingsModal.js
  src/components/Webhooks/WebhookSettingsPopper.js
  src/components/Webhooks/Webhooks.js
  src/components/Webhooks/WebhooksPage.js
  src/reducers/webhooks.js
  src/routers/AppRouter.js
  src/styles/service-forms.scss
  src/styles/webhooks.scss
Labels: enhancement

#58 Feature/service ssh
  src/actions/connections.js
  src/actions/spotify.js
  src/components/Connections/AddConnection.js
  src/components/LoginSignUp/SignUpForm.js
  src/components/SSH/ConnectionForm.js
  src/components/SSH/ConnectionFormModal.js
  src/components/SSH/ConnectionFormPopper.js
  src/components/SSH/ExtractKey.js
  src/components/SSH/UserKey.js
  src/components/SSH/UserPass.js
  src/components/Scenarios/ScenarioNodes.js
  src/components/Services/SSH/ExecuteCommand/Form.js
  src/components/Services/SSH/SidebarItem.js
  src/components/Services/Spotify/GetTopTracks/Form.js
  src/components/Services/Spotify/SaveToPlaylist/Form.js
  src/components/Services/Spotify/WatchPlaylist/Form.js
  src/components/Services/Webhook/CustomWebhook/Form.js
  src/components/Services/Webhook/WebhookResponse/Form.js
  src/components/Services/nodeTypes.js
  src/components/Services/services.js
  src/components/Webhooks/AddDataStructure.js
  src/components/Webhooks/QueueDetails.js
  src/components/Webhooks/Webhooks.js
  src/components/Webhooks/WebhooksPage.js
  src/styles/service-forms.scss
  src/styles/ssh.scss
  src/styles/styles.scss
Labels: feature

#59 Tests
  src/tests/actions/connections.test.js
  src/tests/actions/scenarios.test.js
  src/tests/actions/spotify.test.js
  src/tests/actions/webhook.test.js
  src/tests/actions/webhooks.test.js
  src/tests/components/LoginSignUp/LoginForm.test.js
  src/tests/components/LoginSignUp/SignUpForm.test.js
  src/tests/components/NotFoundPage.test.js
  src/tests/components/Spotify/AddToPlaylistForm.test.js
  src/tests/components/Spotify/TrackInfo.test.js
  src/tests/components/Spotify/WatchPlaylist.test.js
  src/tests/components/Spotify/__snapshots__/AddToPlaylistForm.test.js.snap
  src/tests/components/Spotify/__snapshots__/TrackInfo.test.js.snap
  src/tests/components/Spotify/__snapshots__/WatchPlaylist.test.js.snap
  src/tests/components/Webhooks/Webhook.test.js
  src/tests/components/Webhooks/Webhooks.test.js
  src/tests/components/Webhooks/__snapshots__/Webhook.test.js.snap
  src/tests/components/Webhooks/__snapshots__/Webhooks.test.js.snap
  src/tests/components/__snapshots__/NotFoundPage.test.js.snap
  src/tests/reducers/connections.test.js
  src/tests/reducers/scenario.test.js
  src/tests/reducers/spotify.test.js
  src/tests/reducers/webhooks.test.js
Labels: enhancement

#60 Feature/scenario history
  src/actions/histories.js
  src/actions/history.js
  src/components/Histories/Histories.js
  src/components/Histories/HistoriesPage.js
  src/components/Histories/NoData.js
  src/components/Histories/Record.js
  src/components/Histories/TableLoader.js
  src/components/Histories/breadcrumbsParts.js
  src/components/History/Accordions.js
  src/components/History/AccordionsLoader.js
  src/components/History/CustomAccordion.js
  src/components/History/History.js
  src/components/History/HistoryPage.js
  src/components/History/Info.js
  src/components/History/LabelValue.js
  src/components/History/Status.js
  src/components/History/breadcrumbsParts.js
  src/components/Layout/AppbarBread.js
  src/components/Scenarios/AddScenario.js
  src/components/Scenarios/Scenario.js
  src/components/Scenarios/Scenarios.js
  src/reducers/histories.js
  src/reducers/history.js
  src/routers/AppRouter.js
  src/store/configureStore.js
  src/styles/breadcrumbs.js
  src/styles/layout/main.scss
  src/styles/sketchpad/icons.scss
Labels: feature

#72 Feature/landing page
  package.json
  src/components/LandingPage/FeaturesSection.js
  src/components/LandingPage/Footer.js
  src/components/LandingPage/Header.js
  src/components/LandingPage/IntroSection.js
  src/components/LandingPage/JoinSection.js
  src/components/LandingPage/LandingButtons.js
  src/components/LandingPage/LandingPage.js
  src/components/LandingPage/ServicesSection.js
  src/components/LandingPage/particlesParams.js
  src/components/Layout/CustomDrawer.js
  src/components/LoginSignUp/AuthButtons.js
  src/routers/PublicRoute.js
  src/styles/assets/Legato-Logo.png
  src/styles/assets/landing/nomad.svg
  src/styles/assets/landing/scenario.png
  src/styles/assets/landing/sketchpad.png
  src/styles/assets/logo.png
  src/styles/assets/services/discord_256.png
  src/styles/assets/services/discord_64.png
  src/styles/assets/services/github_256.png
  src/styles/assets/services/github_64.png
  src/styles/assets/services/gmail_256.png
  src/styles/assets/services/gmail_64.png
  src/styles/assets/services/http_256.png
  src/styles/assets/services/http_64.png
  src/styles/assets/services/regex_256.png
  src/styles/assets/services/regex_64.png
  src/styles/assets/services/repeater_256.png
  src/styles/assets/services/repeater_64.png
  src/styles/assets/services/sleep_256.png
  src/styles/assets/services/sleep_64.png
  src/styles/assets/services/spotify_256.png
  src/styles/assets/services/spotify_64.png
  src/styles/assets/services/ssh_256.png
  src/styles/assets/services/ssh_64.png
  src/styles/assets/services/telegram_256.png
  src/styles/assets/services/telegram_64.png
  src/styles/assets/services/webhooks_256.png
  src/styles/assets/services/webhooks_64.png
  src/styles/landing-dialogs.scss
  src/styles/landing-page.scss
  src/styles/service-icons.scss
  src/styles/styles.scss
Labels: feature

#73 Feature/theme
  src/components/Connections/AddConnection.js
  src/components/Connections/Connection.js
  src/components/Connections/ConnectionsPage.js
  src/components/LandingPage/IntroSection.js
  src/components/LandingPage/JoinSection.js
  src/components/Scenarios/AddScenario.js
  src/components/Scenarios/Scenario.js
  src/components/Sketchpad/Edges/CustomEdge.js
  src/components/Sketchpad/SketchpadActivation.js
  src/components/Sketchpad/SketchpadControl.js
  src/components/Sketchpad/SketchpadTitle.js
  src/components/Webhooks/WebhooksPage.js
  src/components/YesNoModal.js
  src/styles/base/_settings.scss
  src/styles/base/theme.js
  src/styles/breadcrumbs.js
  src/styles/connections.scss
  src/styles/landing-dialogs.scss
  src/styles/landing-page.scss
  src/styles/layout/main.scss
  src/styles/layout/notification.scss
  src/styles/layout/preloader.scss
  src/styles/service-icons.scss
  src/styles/serviceform.scss
  src/styles/sketchpad/element.scss
  src/styles/sketchpad/sketchpad.scss
  src/styles/styles.scss
  src/styles/webhooks.scss
Labels: enhancement

#74 Feature/icons
  src/actions/connections.js
  src/components/Connections/Connection.js
  src/components/Scenarios/ScenarioNodes.js
  src/components/ServiceIcon.js
  src/components/Services/Github/CustomServiceNode.js
  src/components/Services/Github/SidebarItem.js
  src/components/Services/HTTP/CustomServiceNode.js
  src/components/Services/HTTP/SidebarItem.js
  src/components/Services/SSH/CustomServiceNode.js
  src/components/Services/SSH/SidebarItem.js
  src/components/Services/Spotify/CustomServiceNode.js
  src/components/Services/Spotify/SidebarItem.js
  src/components/Services/Telegram/CustomServiceNode.js
  src/components/Services/Telegram/SidebarItem.js
  src/components/Services/Webhook/CustomServiceNode.js
  src/components/Services/Webhook/SidebarItem.js
  src/styles/scenarios.scss
  src/styles/sketchpad/element.scss
  src/styles/sketchpad/icons.scss
  src/styles/sketchpad/sketchpad.scss
Labels: enhancement

#77 Fix/sketchpad
  src/actions/sketchpad.js
  src/components/Connections/Connections.js
  src/components/LandingPage/ServicesSection.js
  src/components/Layout/CustomDrawer.js
  src/components/Layout/MenuItems.js
  src/components/Loaders/ListLoader.js
  src/components/Loaders/Preloader.js
  src/components/SSH/Keys.js
  src/components/Scenarios/Scenario.js
  src/components/Scenarios/ScenarioActivation.js
  src/components/Scenarios/ScenarioDelete.js
  src/components/Scenarios/ScenarioHistory.js
  src/components/Scenarios/ScenarioNodes.js
  src/components/Scenarios/ScenarioTime.js
  src/components/Scenarios/Scenarios.js
  src/components/Scenarios/intervalToText.js
  src/components/ServiceIcon.js
  src/components/ServiceIcons/LandingServiceIcon.js
  src/components/ServiceIcons/NodeServiceIcon.js
  src/components/ServiceIcons/ScenarioServiceIcon.js
  src/components/ServiceIcons/ServiceIcon.js
  src/components/ServiceIcons/SidebarServiceIcon.js
  src/components/Services/Github/CustomServiceNode.js
  src/components/Services/Github/SidebarItem.js
  src/components/Services/HTTP/CustomServiceNode.js
  src/components/Services/HTTP/SidebarItem.js
  src/components/Services/SSH/CustomServiceNode.js
  src/components/Services/SSH/SidebarItem.js
  src/components/Services/Spotify/CustomServiceNode.js
  src/components/Services/Spotify/SidebarItem.js
  src/components/Services/Telegram/CustomServiceNode.js
  src/components/Services/Telegram/SidebarItem.js
  src/components/Services/Webhook/CustomServiceNode.js
  src/components/Services/Webhook/SidebarItem.js
  src/components/Sketchpad/Nodes/Node.js
  src/components/Sketchpad/Nodes/NodePopover.js
  src/components/Sketchpad/Sketchpad.js
  src/components/Sketchpad/SketchpadControl.js
  src/components/Static/DummyPage.js
  src/components/Static/NoItem.js
  src/components/Static/NotFoundPage.js
  src/components/Webhooks/Webhooks.js
  src/index.js
  src/reducers/nodePopover.js
  src/routers/AppRouter.js
  src/store/configureStore.js
  src/styles/layout/layout.js
  src/styles/layout/main.scss
  src/tests/components/NotFoundPage.test.js
Labels: bug, feature

#79 Feature/toolbox
  src/components/Services/ToolBox/Repeater/CustomServiceNode.js
  src/components/Services/ToolBox/Repeater/Form.js
  src/components/Services/ToolBox/Repeater/Node.js
  src/components/Services/ToolBox/Repeater/SidebarItem.js
  src/components/Services/ToolBox/Sleep/CustomServiceNode.js
  src/components/Services/ToolBox/Sleep/Form.js
  src/components/Services/ToolBox/Sleep/Node.js
  src/components/Services/ToolBox/Sleep/SidebarItem.js
  src/components/Services/ToolBox/ToolboxSidebarItem.js
  src/components/Services/nodeTypes.js
  src/components/Services/services.js
  src/components/Sketchpad/Sidebar/SketchpadSidebar.js
  src/styles/service-forms.scss
Labels: feature

#81 Feature/sketchpad status
  src/actions/sketchpad.js
  src/actions/sketchpadStatus.js
  src/components/Scenarios/ScenarioNodes.js
  src/components/Sketchpad/Sidebar/MenuItem.js
  src/components/Sketchpad/Sketchpad.js
  src/components/Sketchpad/SketchpadControl.js
  src/components/Sketchpad/Status.js
  src/reducers/sketchpadStatus.js
  src/store/configureStore.js
  src/utils/sketchpadConverter.js
Labels: bug, feature

#80 Feature/GitHub
  src/actions/connections.js
  src/components/Connections/AddConnection.js
  src/components/Connections/Redirect.js
  src/components/Services/Github/CreateIssue/Form.js
  src/components/Services/Github/CreateIssue/Node.js
  src/components/Services/Github/CreatePullRequest/Form.js
  src/components/Services/Github/CreatePullRequest/Node.js
  src/components/Services/nodeTypes.js
  src/components/Services/services.js
  src/styles/service-forms.scss
Labels: feature
