Repository Ragnacodes/Legato-Frontend, pull requests merged in 2021-06, with the labels that each got.

#84 Feature/connections v3
  src/components/Connections/AddConnection.js
  src/components/Connections/Connection.js
  src/components/Connections/ConnectionsPage.js
  src/components/Connections/TelegramBot.js
  src/components/Services/Telegram/SendMessage/Form.js
  src/components/Services/Telegram/getChatMember/Form.js
  src/styles/connections.scss
  src/styles/service-forms.scss
Labels: enhancement, feature

#82 Feature/discord
  src/actions/discord.js
  src/components/SSH/ConnectionForm.js
  src/components/Scenarios/ScenarioNodes.js
  src/components/Services/Discord/CustomServiceNode.js
  src/components/Services/Discord/Message.js
  src/components/Services/Discord/MessageList.js
  src/components/Services/Discord/PinMessage/Form.js
  src/components/Services/Discord/PinMessage/Node.js
  src/components/Services/Discord/ReactToMessage/Form.js
  src/components/Services/Discord/ReactToMessage/Node.js
  src/components/Services/Discord/SendMessage/Form.js
  src/components/Services/Discord/SendMessage/Node.js
  src/components/Services/Discord/SidebarItem.js
  src/components/Services/SSH/ExecuteCommand/Form.js
  src/components/Services/Spotify/SaveToPlaylist/Form.js
  src/components/Services/Webhook/CustomWebhook/Form.js
  src/components/Services/nodeTypes.js
  src/components/Services/services.js
  src/components/Sketchpad/Sidebar/SketchpadSidebar.js
  src/reducers/discord.js
  src/reducers/spotify.js
  src/store/configureStore.js
  src/styles/service-forms.scss
  src/tests/actions/discord.test.js
  src/tests/actions/spotify.test.js
  src/tests/reducers/discord.test.js
Labels: feature

#85 Feature/webhook v3
  src/actions/spotify.js
  src/actions/webhooks.js
  src/components/ServiceIcons/SidebarServiceIcon.js
  src/components/Services/SSH/ExecuteCommand/Form.js
  src/components/Services/Spotify/GetTopTracks/Form.js
  src/components/Services/Spotify/SaveToPlaylist/Form.js
  src/components/Services/ToolBox/Sleep/Form.js
  src/components/Services/Webhook/CustomWebhook/Form.js
  src/components/Sketchpad/Sidebar/SketchpadSidebar.js
  src/components/Webhooks/AdvancedSettings.js
  src/components/Webhooks/GeneralSettings.js
  src/components/Webhooks/Webhook.js
  src/components/Webhooks/WebhooksPage.js
  src/components/YesNoModal.js
  src/reducers/webhooks.js
  src/styles/service-forms.scss
  src/styles/sketchpad/sketchpad.scss
  src/styles/webhooks.scss
Labels: enhancement

#86 Feature/history log
  package.json
  src/actions/connections.js
  src/actions/histories.js
  src/actions/history.js
  src/components/Histories/Histories.js
  src/components/Histories/Record.js
  src/components/Histories/Status.js
  src/components/History/CustomAccordion.js
  src/components/History/History.js
  src/components/History/Info.js
  src/components/History/Message.js
  src/components/History/breadcrumbsParts.js
  src/components/ServiceIcons/SidebarServiceIcon.js
  src/components/Sketchpad/Logs.js
  src/components/Sketchpad/Sidebar/SidebarItem.js
  src/components/Sketchpad/Sidebar/SketchpadSidebar.js
  src/components/Sketchpad/Sketchpad.js
  src/components/Sketchpad/SketchpadControl.js
  src/components/Sketchpad/SketchpadPage.js
  src/reducers/histories.js
  src/reducers/history.js
  src/styles/sketchpad/sketchpad.scss
  src/utils/serviceConverter.js
Labels: feature

#87 Feature/gmail send email
  src/components/Scenarios/ScenarioNodes.js
  src/components/Services/Gmail/CustomServiceNode.js
  src/components/Services/Gmail/SidebarItem.js
  src/components/Services/Gmail/sendEmail/Form.js
  src/components/Services/Gmail/sendEmail/Node.js
  src/components/Services/nodeTypes.js
  src/components/Services/services.js
  src/components/Sketchpad/Sidebar/SketchpadSidebar.js
  src/utils/serviceConverter.js
Labels: feature

#88 Setup cd
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/components/Services/Webhook/CustomWebhook/Form.js
Labels: feature

#91 [fix] change redirect from localhost to abstergo
  src/components/Connections/Redirect.js
Labels: bug
