Repository Ragnacodes/Legato-Frontend, pull requests merged in 2021-04, with the labels that each got.

#34 Feature/layout v2
  src/components/Connections/Connections.js
  src/components/Dashboard/Dashboard.js
  src/components/DummyPage.js
  src/components/Layout/DummyPage.js
  src/components/Layout/NoItem.js
  src/components/Layout/NotFoundPage.js
  src/components/Layout/Notification.js
  src/components/Layout/PageTitle.js
  src/components/Layout/Preloader.js
  src/components/LoginSignUp/LoginForm.js
  src/components/LoginSignUp/SignUpForm.js
  src/components/NotFoundPage.js
  src/components/Scenarios/Scenarios.js
  src/components/Webhooks/Webhook.js
  src/components/Webhooks/Webhooks.js
  src/index.js
  src/routers/AppRouter.js
  src/styles/assets/blank-page.svg
  src/styles/assets/empty-box.svg
  src/styles/assets/page-not-found.svg
  src/styles/layout/main.scss
  src/styles/layout/preloader.scss
  src/styles/styles.scss
Labels: enhancement, feature

#35 Feature/onclick textfield
  src/components/OnClickTextField.js
  src/components/Sketchpad/SketchpadTitle.js
  src/components/Webhooks/Webhook.js
  src/styles/onclick-textfield.scss
  src/styles/styles.scss
  src/styles/webhooks.scss
Labels: enhancement

#37 [feat] popover component style
  src/components/Popover.js
  src/styles/popover.scss
  src/styles/styles.scss
  src/styles/webhooks.scss
Labels: enhancement, feature

#42 Feature/sketchpad http
  src/components/Services/HTTP/MakeRequest/Form.js
  src/components/Sketchpad/SketchpadControl.js
  src/styles/serviceform.scss
Labels: feature
